<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Octo.Common.DistributionEventHub</AssemblyName>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Meshmakers.Octo.Common.DistributionEventHub</PackageId>
        <RootNamespace>Meshmakers.Octo.Common.DistributionEventHub</RootNamespace>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
        <OutputPath>..\..\bin\$(Configuration)\</OutputPath>
        <DocumentationFile>..\..\bin\$(Configuration)\$(AssemblyName).xml</DocumentationFile>
        <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
        <TargetFramework />
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Meshmakers.Common.Shared" Version="$(MeshmakerVersion)" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.3" />
        <PackageReference Include="MassTransit.Hangfire" Version="8.2.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
        <PackageReference Include="MongoDB.Driver" Version="2.26.0" />
        <PackageReference Include="MongoDB.Driver.GridFS" Version="2.26.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath />
            <Link>LICENSE</Link>
        </None>
    </ItemGroup>

</Project>