<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>octo-distevents-monitor</AssemblyName>
        <PackageId>SampleCli</PackageId>
        <RootNamespace>SampleCli</RootNamespace>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)'!='DebugL'">
        <PackageReference Include="Meshmakers.Common.CommandLineParser" Version="4.0.2412.18002" />
        <PackageReference Include="Meshmakers.Common.Configuration" Version="4.0.2412.18002" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)'=='DebugL'">
        <PackageReference Include="Meshmakers.Common.CommandLineParser" Version="4.0.2412.18002" />
        <PackageReference Include="Meshmakers.Common.Configuration" Version="4.0.2412.18002" />
    </ItemGroup>

    <ItemGroup>
         <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
        <PackageReference Include="NLog" Version="5.3.4" />
        <PackageReference Include="NLog.Extensions.Logging" Version="5.3.15" />
        <PackageReference Include="NLog.Schema" Version="5.3.4" />
    </ItemGroup>

    <ItemGroup>
      <None Update="nlog.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SampleEvents\SampleEvents.csproj" />
    </ItemGroup>
        
</Project>
