<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>octo-distevents-monitor</AssemblyName>
        <PackageId>SampleCli</PackageId>
        <RootNamespace>SampleCli</RootNamespace>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Meshmakers.Common.CommandLineParser" Version="$(MeshmakerVersion)" />
        <PackageReference Include="Meshmakers.Common.Configuration" Version="$(MeshmakerVersion)" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
        <PackageReference Include="NLog" Version="6.1.3" />
        <PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
    </ItemGroup>

    <ItemGroup>
        <None Update="nlog.config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DistributionEventHub.MongoDB\DistributionEventHub.MongoDB.csproj" />
        <ProjectReference Include="..\SampleEvents\SampleEvents.csproj" />
    </ItemGroup>

</Project>
