name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    exclude:
      - '*'

variables:
  buildConfiguration: 'Release'
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/r')]
  MajorVersion: 0
  MinorVersion: 0

stages:
 - stage: Build
   jobs:
    - job: buildAndTest
      displayName: "Build nuget and execute tests"
      pool:
        name: Gerald-Local-Linux
      steps:
      - template: update-build-number.yml
      - checkout: self
        clean: true
        submodules: true
      - template: set-version.yml
      - task: DotNetCoreCLI@2
        displayName: 'Build src'
        inputs:
          command: 'build'
          projects: |
            src/**/*.csproj
          arguments: '--configuration $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'Test'
        inputs:
          command: 'test'
          arguments: '--configuration $(buildConfiguration)'
          projects: |
            **/*Tests.csproj
            !**/*SystemTests.csproj
          testRunTitle: 'CI'
      - task: PublishSymbols@2
        displayName: Publish symbols path
        continueOnError: True
        inputs:
          SearchPattern: '**\bin\**\*.pdb'
          PublishSymbols: false
          SymbolServerType: TeamServices
      - task: CopyFiles@2
        displayName: 'Copy Files from $(Build.SourcesDirectory)/bin/$(BuildConfiguration)/**/*.nupkg to $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: $(Build.SourcesDirectory)
          Contents: |
            bin/$(BuildConfiguration)/**/*.nupkg
          TargetFolder: $(build.artifactstagingdirectory)
      - task: PowerShell@2
        displayName: 'Create versioninfo file'
        inputs:
          targetType: 'inline'
          script: |
              New-Item $(build.artifactstagingdirectory)/versioninfo.txt
              Set-Content $(build.artifactstagingdirectory)/versioninfo.txt $(Build.BuildNumber)
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: local'
        inputs:
          ArtifactName: local
      - template: push-nuget-package.yml         
