name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - test/*
      - main
  tags:
    exclude:
      - '*'

variables:
  - group: ApiKeys-mm-cloud
  - group: OctoDefault
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: buildConfiguration
    value: 'Release'
  - name: buildPlatform
    value: 'Any CPU'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - name: isTest
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/test') }}

stages:
 - stage: Build
   jobs:
    - job: buildAndTest
      displayName: "Build nuget and execute tests"
      pool:
        name: meshmakers-ci-agents
      steps:
      - template: update-build-number.yml
      - checkout: self
        clean: true
        submodules: true
      - template: set-version.yml
      - task: DotNetCoreCLI@2
        displayName: 'Build src'
        inputs:
          command: 'build'
          projects: |
            src/**/*.csproj
          arguments: '--configuration $(buildConfiguration) /p:OctoNugetPrivateServer=$(nugetPrivateServer)'
      - task: DotNetCoreCLI@2
        displayName: 'Test'
        inputs:
          command: 'test'
          arguments: '--configuration $(buildConfiguration) /p:OctoNugetPrivateServer=$(nugetPrivateServer)'
          projects: |
            **/*Tests.csproj
            !**/*SystemTests.csproj
          testRunTitle: 'CI'
      - template: handle-artifacts.yml
      - template: push-nuget-package.yml
