<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="MassTransit.MongoDb" Version="8.1.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SampleEvents\SampleEvents.csproj" />
  </ItemGroup>
</Project>
