<Project Sdk="Microsoft.NET.Sdk.Worker">
    <PropertyGroup>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MassTransit.MongoDb" Version="[8.5.7]" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\SampleEvents\SampleEvents.csproj" />
    </ItemGroup>
</Project>
